ListenAddress: ":8080"
DB:
  ConnectionString: "mongodb://localhost:27017"
  DatabaseName: "test"
  CollectionName: "users"
AccessTokenMinuteLifespan: "15"
RefreshTokenHourLifespan: "24"
ApiSecret: "answeris42"